### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by DavidFB94** [Damitwhy/Team4-Sep2024-Hackathon#26]
Example content:

- Who we are as a team
- Who was SCRUM master
- Link to repo, live site?
- Describe project
- How to clone the project (deployment, installs etc)
- Basic instructions
- Link to Kanban (set public)
- Libraries, sources, screenshots etc

**Comment by Damitwhy** [comment]
Read the .pdf for Hackathon for details
Images of features
